#!/bin/sh
nl='
'
shcat() {
  while IFS= read -r p || [ "$p" ]; do
    printf '%s' "$p$nl"
  done
}
case "$1" in
  "") in="$(shcat <&0)";;
  *) in="$(shcat <"$1")"
esac

## Read the `shsh.conf` file, if it exists.
for d in $PWD $XDG_CONFIG_HOME/shsh $HOME/.config/shsh # current list of possible locations
do
    if [ -d "${d}" ] && [ -f "${d}/shsh.conf" ]
    then
        . ${d}/shsh.conf
        break # reads the first one found
    else continue
    fi
done

## Setting the submod paths to user-configured ones, otherwise defaulting to the defaults.
modpaths="${user_modpaths:-$PWD}"    # folder where submods can be found
pshrng_DIR="${user_pshrng_DIR:-rng}" # name of the psh-prng folder
pshfc_DIR="${user_pshfc_DIR:-com}"   # name of the psh-fc folder
pshfr_DIR="${user_pshfr_DIR:-math}"  # name of the psh-fractional folder
pshfrPATH="${user_pshfrPATH:-${modpaths}/math}" # needed by psh-rpn
export pshfrPATH # only pshfrPATH is needed outside currently

while IFS= read -r p || [ "$p" ]; do
  IFS=" "; for i in $p; do
    case "$i" in
      '[') TEST=0;;
      ']') unset TEST; TESTvar="${TESTvar+$TESTvar } ]"
    esac
    [ "$TEST" ] && {
      [ "$i" = '[' ] && continue
      TESTvar="${TESTvar+$TESTvar }$i"
    }
    [ ! "$TEST" ] && {
      unset IFS; [ "$TESTvar" ] && {
        p="${modpaths}/${pshfc_DIR}/com $p"
        #echo "$p" >&2
      }
    } && unset TESTvar
    # $TEST is not a test variable, [/[[ is also test
  done
  printf '%s' "$p$nl"
done << EOF
$in
EOF
